# fly.toml file generated for gerador-nomes on 2022-08-31T15:55:39+01:00

app = "gerador-nomes"
kill_signal = "SIGINT"
kill_timeout = 5

# [build]
#   builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  PRIMARY_REGION = "ams"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  web = "bundle exec ruby app.rb -p 8080"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
